name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Changed to write to allow creating releases
  pages: write
  id-token: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: latest

    - name: Install dependencies
      run: npm install

    - name: Build and copy assets
      run: |
        npm run build
        npm run postbuild

    - name: Setup Pages
      uses: actions/configure-pages@v6

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
